spring:
  application:
    name: apt-gateway
server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    eureka:
      path: /eureka/**
      serviceId: eureka-client

